
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfwmbtjpubusnbfzargh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmd21idGpwdWJ1c25iZnphcmdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MjA2NjYsImV4cCI6MjA1OTI5NjY2Nn0.tLxIhrAIQONGEN8U-ta6153l6nSV5j1JeKzkAAZyrqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
