// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://papouwsgmlpjstuxxpmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhcG91d3NnbWxwanN0dXh4cG1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MTg3MzEsImV4cCI6MjA1OTE5NDczMX0.cXvXFv4hOiCPN-0usFT1bfU7StIG118WkgeHPizl4Go";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);